<?php
/**
* ================= doc ====================
* FILENAME     : SumberDana.php
* @package     : SumberDana
* scope        : PUBLIC
* @Created     : 2018-09-27
* @Modified    : 2018-09-27
* @Analysts    : Anggi Ayu Meidamara <meidamara@gmail.com>
* @Author      : Rochmad Widianto <widiantorochmad@gmail.com>
* @copyright   : Copyright (c) 2018
* ================= doc ====================
*/

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sumberdana extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('MSumberdana');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $sumberdana = $this->MSumberdana->get_all();

        $data = array(
            'sumberdana_data' => $sumberdana
        );

        $this->template->display('ref_sumberdana/ref_sumberdana_list', $data);
    }

    public function read($id) 
    {
        $row = $this->MSumberdana->get_by_id($id);
        if ($row) {
            $data = array(
		'sumberdanaId' => $row->sumberdanaId,
		'sumberdanaKode' => $row->sumberdanaKode,
		'sumberdanaNama' => $row->sumberdanaNama,
	    );
            $this->template->display('ref_sumberdana/ref_sumberdana_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sumberdana'));
        }
    }

    public function create() 
    {
        $data = array(
            'style_aksi' => 'success',
            'label_aksi' => 'Tambah',
            'action' => site_url('sumberdana/create_action'),
	    'sumberdanaId' => set_value('sumberdanaId'),
	    'sumberdanaKode' => set_value('sumberdanaKode'),
	    'sumberdanaNama' => set_value('sumberdanaNama'),
	);
        $this->template->display('ref_sumberdana/ref_sumberdana_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'sumberdanaKode' => $this->input->post('sumberdanaKode',TRUE),
		'sumberdanaNama' => $this->input->post('sumberdanaNama',TRUE),
	    );

            $this->MSumberdana->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('sumberdana'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->MSumberdana->get_by_id($id);

        if ($row) {
            $data = array(
                'style_aksi' => 'warning',
                'label_aksi' => 'Ubah',
                'action' => site_url('sumberdana/update_action'),
		'sumberdanaId' => set_value('sumberdanaId', $row->sumberdanaId),
		'sumberdanaKode' => set_value('sumberdanaKode', $row->sumberdanaKode),
		'sumberdanaNama' => set_value('sumberdanaNama', $row->sumberdanaNama),
	    );
            $this->template->display('ref_sumberdana/ref_sumberdana_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sumberdana'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) { // ini yg akan melaktext, dll, sesuai setting yg
            $this->update($this->input->post('sumberdanaId', TRUE));
        } else {
            $data = array(
		'sumberdanaKode' => $this->input->post('sumberdanaKode',TRUE),
		'sumberdanaNama' => $this->input->post('sumberdanaNama',TRUE),
	    );

            $this->MSumberdana->update($this->input->post('sumberdanaId', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('sumberdana'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->MSumberdana->get_by_id($id);

        if ($row) {
            $this->MSumberdana->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('sumberdana'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sumberdana'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('sumberdanaKode', 'sumberdanaKode', 'trim|required');
	$this->form_validation->set_rules('sumberdanaNama', 'sumberdanaNama', 'trim|required');

	$this->form_validation->set_rules('sumberdanaId', 'sumberdanaId', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }


}

/* End of file Sumberdana.php */
/* Location: ./application/controllers/Sumberdana.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-21 19:10:14 */
/* http://harviacode.com */